apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
  labels:
    name: dummy-pod
spec:
  containers:
    - name: ubuntu
      image: alpine:3.16
      command:
        - "sleep"
        - "infinity"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: credstore
          mountPath: /etc/config
  volumes:
    - name: credstore
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: credstore-credentials
