apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: credstore-credentials
spec:
  provider: credstore
  parameters:
    credentials: |
      - name: my-password
        namespace: prod
        type: password
        fileName: myPassword.txt
      - name: my-encryption-key
        namespace: prod
        type: key
        fileName: myKey.txt
