kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: credstore-csi-provider
  namespace: csi
  labels:
    app: credstore-csi-provider
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: credstore-csi-provider
  template:
    metadata:
      labels:
        app: credstore-csi-provider
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      automountServiceAccountToken: false
      containers:
        - name: provider
          image: ghcr.io/kloyan/credstore-csi-provider:v1.1.0
          args:
            - --service-key-path=/etc/credentials/service-key.json
            - --provider-path=/provider
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - name: provider-vol
              mountPath: /provider
            - name: service-key-vol
              mountPath: /etc/credentials
      volumes:
        - name: provider-vol
          hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
        - name: service-key-vol
          secret:
            secretName: credstore-service-key
