namespace: csi
helmCharts:
- name: secrets-store-csi-driver
  repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  releaseName: secrets-store-csi-driver
  includeCRDs: true
  version: 1.3.2
  namespace: csi
  valuesInline:
    enableSecretRotation: true
    rotationPollInterval: "300s"
    syncSecret:
      enabled: false
resources:
- namespace.yaml
- daemonset.yaml
secretGenerator:
- name: credstore-service-key
  files:
  - service-key.json=service-key.json
